package main

import (
	"bufio"
	"debug/elf"
	"encoding/hex"
	"flag"
	"fmt"
	"io"
	"os"
	"strconv"
	"strings"
)

const version = "0.1.1"

type multiFlag []string

func (m *multiFlag) String() string {
	return strings.Join(*m, ", ")
}

func (m *multiFlag) Set(value string) error {
	*m = append(*m, value)
	return nil
}

type options struct {
	HasFirmware  bool
	BaseAddr     uint32
	ShowSections bool
	ChunkSize    int
}

func usage() {
	fmt.Println(`Usage:
elf2vkp-go -i patch.elf [options]

Options:
-i <file>              Input ELF patch
-f <file>              Firmware BIN (optional)
-b <addr>              Firmware base address (default: 0)
-o <file>              Output VKP (default: stdout)

--header <text>        Add header line (repeatable)
--header-from-file <f> Read header lines from file

--section-names        Show ELF section names
--chunk-size <n>       Bytes per line (default: 16)

-v, --version          Show version
-h, --help             Show help`)
}

func emitVKP(
	w io.Writer,
	addr uint32,
	oldData []byte,
	newData []byte,
	opts options,
	sectionName string,
) {
	if opts.ShowSections {
		fmt.Fprintf(w, "; section %s\n", sectionName)
	}

	for i := 0; i < len(newData); i += opts.ChunkSize {
		end := i + opts.ChunkSize
		if end > len(newData) {
			end = len(newData)
		}

		newBytes := newData[i:end]
		offset := addr + uint32(i)

		if opts.HasFirmware {
			oldBytes := oldData[i:end]
			fmt.Fprintf(
				w,
				"%08X: %s %s\n",
				offset,
				strings.ToUpper(hex.EncodeToString(oldBytes)),
				strings.ToUpper(hex.EncodeToString(newBytes)),
			)
		} else {
			fmt.Fprintf(
				w,
				"%08X: %s\n",
				offset,
				strings.ToUpper(hex.EncodeToString(newBytes)),
			)
		}
	}
}

func main() {
	var (
		input        string
		fullflash    string
		baseStr      string
		output       string
		headerFile   string
		showHelp     bool
		showVersion  bool
		showSections bool
		chunkSize    int
		headers      multiFlag
	)

	flag.StringVar(&input, "i", "", "")
	flag.StringVar(&fullflash, "f", "", "")
	flag.StringVar(&baseStr, "b", "0", "")
	flag.StringVar(&output, "o", "", "")
	flag.Var(&headers, "header", "")
	flag.StringVar(&headerFile, "header-from-file", "", "")
	flag.BoolVar(&showSections, "section-names", false, "")
	flag.IntVar(&chunkSize, "chunk-size", 16, "")

	flag.BoolVar(&showHelp, "h", false, "")
	flag.BoolVar(&showHelp, "help", false, "")
	flag.BoolVar(&showVersion, "v", false, "")
	flag.BoolVar(&showVersion, "version", false, "")

	flag.Parse()

	if showHelp {
		usage()
		return
	}

	if showVersion {
		fmt.Println("elf2vkp-go", version)
		return
	}

	if input == "" {
		usage()
		os.Exit(1)
	}

	if chunkSize <= 0 {
		fmt.Fprintln(os.Stderr, "chunk-size must be > 0")
		os.Exit(1)
	}

	baseAddr64, err := strconv.ParseUint(strings.TrimPrefix(baseStr, "0x"), 16, 32)
	if err != nil {
		fmt.Fprintln(os.Stderr, "invalid base address")
		os.Exit(1)
	}
	baseAddr := uint32(baseAddr64)

	// Output selection
	var out io.Writer = os.Stdout
	var outFile *os.File

	if output != "" {
		outFile, err = os.Create(output)
		if err != nil {
			fmt.Fprintln(os.Stderr, "failed to create output file")
			os.Exit(1)
		}
		defer outFile.Close()
		out = outFile
	}

	// Emit headers
	for _, h := range headers {
		if !strings.HasPrefix(h, ";") {
			h = ";" + h
		}
		fmt.Fprintln(out, h)
	}

	if headerFile != "" {
		f, err := os.Open(headerFile)
		if err != nil {
			fmt.Fprintln(os.Stderr, "failed to open header file")
			os.Exit(1)
		}
		sc := bufio.NewScanner(f)
		for sc.Scan() {
			fmt.Fprintln(out, sc.Text())
		}
		f.Close()
	}

	// Load firmware if provided
	var firmware []byte
	hasFirmware := false

	if fullflash != "" {
		firmware, err = os.ReadFile(fullflash)
		if err != nil {
			fmt.Fprintln(os.Stderr, "failed to read firmware")
			os.Exit(1)
		}
		hasFirmware = true
	}

	opts := options{
		HasFirmware:  hasFirmware,
		BaseAddr:     baseAddr,
		ShowSections: showSections,
		ChunkSize:    chunkSize,
	}

	ef, err := elf.Open(input)
	if err != nil {
		fmt.Fprintln(os.Stderr, "failed to open ELF")
		os.Exit(1)
	}
	defer ef.Close()

	for _, sec := range ef.Sections {
		if sec.Type != elf.SHT_PROGBITS ||
			sec.Size == 0 ||
			sec.Flags&elf.SHF_ALLOC == 0 {
			continue
		}

		data, err := sec.Data()
		if err != nil || len(data) == 0 {
			continue
		}

		old := make([]byte, len(data))

		if hasFirmware {
			if sec.Addr < uint64(baseAddr) {
				continue
			}
			offset := sec.Addr - uint64(baseAddr)
			if offset < uint64(len(firmware)) {
				copy(old, firmware[offset:])
			}
		}

		emitVKP(
			out,
			uint32(sec.Addr),
			old,
			data,
			opts,
			sec.Name,
		)
	}

	fmt.Fprintf(out, "; Generated by elf2vkp-go v%s\n", version)
	fmt.Fprintln(out, "; https://github.com/farid1991/elf2vkp-go")
}
